config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: { omniauth_callbacks: 'admins/omniauth_callbacks' }

  # Defines the root path route ("/")
  root "home#index"
  get 'map', to: 'maps#json'
  get 'maps', to: 'maps#index', as: 'maps'
  post 'subscribe', to: 'subscriptions#subscribe', as: 'subscribe'
  get 'unsubscribe', to: 'subscriptions#unsubscribe', as: 'unsubscribe'
  get 'confirm', to: 'subscriptions#confirm', as: 'confirm'
  namespace 'admins' do
    get 'reset-waypoints', to: 'switchboard#reset_waypoints'
    get 'reset-cache', to: 'switchboard#reset_cache'
    get 'reset-all', to: 'switchboard#reset_all'
    get 'login', to: 'switchboard#login'
  end
end

app/models/subscription.rb
# I intend to implement automatic weekly emails summarizing the weeks activities. For now this is just to allow subscriptions
class Subscription < ApplicationRecord
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates_uniqueness_of :email
  before_validation :create_token
  validates_presence_of :token

  def self.subscribe(email)
    subscription = Subscription.find_or_create_by!(email: email)
    token = subscription.token
    email = subscription.email
    # If desired send a confirmation email with callback to validate_email.
    # the callback should contain the emails address and token as parameters
    subscription
  end

  def self.unsubscribe(email, token)
    Subscription.destroy_by(email: email, token: token)
  end

  def self.validate_email(email, token)
    subscription = Subscription.find_by(email: email, token: token)
    subscription.confirmed = true && subscription.save! if subscription
  end

  private

  def create_token
    self.token = SecureRandom.hex(16) unless self.token.present?
  end

  def valid_token?(token)
    token.equal?(self.token)
  end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController

  def subscribe
    email = params[:email]
    subscribed = Subscription.subscribe(email)
    message = subscribed ? 'You have subscribed!' : 'Oops is that email valid?'
    render turbo_stream: turbo_stream.replace('subscription_container',
                                              partial: 'subscriptions/subscribe',
                                              locals: { response: true, message: message })
  end

  def unsubscribe
    email = params[:email]
    token = params[:token]

    success = email && token && Subscription.unsubscribe(email, token)
    render 'subscriptions/unsubscribed', locals: { success: success }
  end

  def confirm
    email = params[:email]
    token = params[:token]
    success = email && token && Subscription.validate_email(email, token)
    render 'subscriptions/confirmed', locals: { success: success }
  end
end

app/views/subscriptions/_subscribe.html.erb
<%= turbo_frame_tag 'subscription_container' do %>
  <% if local_assigns[:response].nil? %>
    <%= form_with url: subscribe_path, method: :post do |form| %>
      <div class="">
        <%= form.label :email, "Email:" %>
        <%= form.email_field :email, class: "rounded py-0 border-gray-500 bg-none outline-none focus:ring-0 focus:border-green" %>
        <%= form.submit "Subscribe", class: 'px-1 mt-2 lg:mt-0 text-lg rounded-md bg-green text-soft-white cursor-pointer hover:bg-green/80' %>
      </div>
    <% end %>
  <% else %>
    <p><%= local_assigns[:message] %></p>
  <% end %>
<% end %>

app/views/subscriptions/confirmed.html.erb
<div class="p-4 w-full text-center  text-4xl text-green">
 Confirm Email
</div>
<% if local_assigns[:success] %>
  <div class="mx-auto">You have confirmed your email!</div>
<% else %>
  <div class="mx-auto">You may click the 'confirm' button in the email with subject "Confirm Email" to ensure safe delivery
    of future emails.
  </div>
<% end %>


<div class="my-8 text-center font-extrabold text-4xl text-green underline">
  <%= link_to 'Home', root_path %>
</div>

app/views/subscriptions/unsubscribed.html.erb
<div class="p-4 w-full text-center  text-4xl text-green">
 Unsubscribe
</div>
<% if local_assigns[:success] %>
  <div class="mx-auto">You have unsubscribed from any future emails.</div>
<% else %>
  <div class="mx-auto">You may click the 'unsubscribed' button at the bottom of any of my email's to unsubscribe from
    future emails.
  </div>
<% end %>


<div class="my-8 text-center font-extrabold text-4xl text-green underline">
  <%= link_to 'Home', root_path %>
</div>